redis:
  addr: "localhost"
  port: "6379"
  password: ""
  db: 0

postgres:
  host: "localhost"
  port: "5432"
  user: "your_user"
  password: "your_password"
  db_name: "your_db"

localhost:
  host: "localhost"
  port: "8080"