redis:
  addr: "localhost"
  port: "6379"
  password: ""
  db: 0

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  db_name: "game"

localhost:
  host: "localhost"
  port: "8080"